### ISSUE TITLE
With version 2.0.0, gauge increment is not availible

### ISSUE THREAD

**Issue by daveauerbach** [postmates/pystatsd#11]
This means that the client is required to keep track of a gauge over long periods of time, potentially across multiple processes. I was under the impression that incrementing a gauge is typical behavior of the statsd protocol. Is it something we can no longer support?

**Comment by blt** [comment]
The increment gauge is a non-standard extension by etsy/statsd which cernan doesn't support. To my knowledge etsy/statsd is the only statsd server to support an increment gauge. 

The client shouldn't have to keep an in-memory value and report it out as a gauge. Depending on what you're measuring it's sufficient to report as either a counter or a gauge and then do a window sum--`msum`--over that time series in wavefront. etl tracking.py [here](https://github.com/postmates/analytics_etl/blob/5f05a755c987e879ab0ffd76b5ce4d878836a5af/etl/tracking.py#L66) could be made into a non-gauge counter. Using a counter will have the benefit of not reseting at system deploy.

Let me know if you have further concerns. We control the whole show--@pulltab and I--so if there are any use-cases that can't be covered by the existing implementation we can extend things.

**Comment by bitglue** [comment]
Isn't etsy/statsd *the* de facto standard since Flickr-StatsD was deprecated?

> Depending on what you're measuring it's sufficient to report as either a counter or a gauge and then do a window sum--i.e. msum--over that time series.

This doesn't exactly get you back to what an incrementing gauge (which would be called a counter if statsd didn't already define that to mean something else). To get back to a counter you'd want to integrate the series, but wavefront doesn't have a (documented) way to do that. So if you want to see a cumulative change from the start to the end of the query period, your'e SOL unless you use incrementing gauges.

Furthermore, incrementing guages is more robust in the presence of metrics dropped between statsd and graphite/wavefront (which I might add, has been happening quite regularly lately). If a counter is dropped, the information about what happened in that period is lost forever and nothing is known about the period where samples were dropped. If an incrementing gauge is dropped, the mean rate of event occurrences over the period where samples are missing can still be correctly calculated. Only the resolution is decreased: accuracy is unaffected.

To make matters worse, wavefronts `msum` and `integrate` functions are really screwy. To use `msum` you must know something about how frequently metrics are reported. For example, `msum(5m, align(1s, 1))` is 300, whereas `msum(5m, align(10s, 1))` is 30. You might think `integrate` would take into account the distance between samples like an integral would, but honestly I can't figure out what it does. `integrate(5m, align(10s, 1))` is 295 (?!) and `integrate(5m, align(1m, 1))` yields some crazy sawtooth pattern that changes as you zoom in and out.

> To my knowledge etsy/statsd is the only statsd server to support an increment gauge.

  - [statsdamon](https://github.com/bitly/statsdaemon#statsdaemon)
  - [statsite](https://github.com/armon/statsite#protocol)
  - [brubeck](https://github.com/github/brubeck/commit/8d089469eac37b33f536ca9d9e7b7f194f9a51da)

**Comment by blt** [comment]
Alright, fair enough. We'll put support in for incrementing gauges. /cc
@pulltab and @tsantero

> Furthermore, incrementing guages is more robust in the presence of
metrics dropped between statsd and graphite/wavefront (which I might add,
has been happening quite regularly lately).

Can you elaborate on this? First I've heard of it.

**Comment by bitglue** [comment]
I guess it's because we keep having issues with the wavefront proxy or something, but there are several instances of gaps where we didn't send any metrics. A couple examples:

https://metrics.wavefront.com/u/yz9gs9hFXw
https://metrics.wavefront.com/u/87mpWWYR76

I know there are more, and there were also times where we just dropped metrics for brief periods, intermittently. Those are harder to find in the history, though.
